const cards = [
    {
        name: "Rose",
        smallImg:"/Flowers-but-better/circle/red-rose-flower-illustration-Rose-Rose-HD-leaf-color-plant-Stem-png-min_2.png",
        largeImg:"/Flowers-but-better/circle/red-rose-flower-illustration-Rose-Rose-HD-leaf-color-plant-Stem-png-min_2.png",
        description: "Roses are iconic flowers known for their beauty and fragrance, symbolizing love.",
        checked: true,
    },
    {
        name: "Tulip",
        smallImg:"/Flowers-but-better/circle/Tulip_Transparent_Image-1525420458_2.png",
        largeImg:"/Flowers-but-better/circle/Tulip_Transparent_Image-1525420458_2.png",
        description: "Tulips are colorful flowers, popular in gardens and symbolizing perfect love.",
        checked: false,
    },
    {
        name: "Sunflower",
        smallImg:"/Flowers-but-better/circle/purepng.com-sunflowersunflowersunflower-plantsunflower-oilyellow-sunflower-1701527749038lczyn_2.png",
        largeImg:"/Flowers-but-better/circle/purepng.com-sunflowersunflowersunflower-plantsunflower-oilyellow-sunflower-1701527749038lczyn_2.png",
        description: "Sunflowers are known for their large yellow petals and seeds, often associated with happiness.",
        checked: false,
    },
    {
        name: "Orchid",
        smallImg:"/Flowers-but-better/circle/pngtree-red-orchid-on-white-background-vibrant-png-image_10174647_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-red-orchid-on-white-background-vibrant-png-image_10174647_2.png",
        description: "Orchids are exotic flowers with intricate designs, symbolizing beauty and strength.",
        checked: false,
    },
    {
        name: "Daffodil",
        smallImg:"/Flowers-but-better/circle/Yellow_Daffodils_PNG_Transparent_Clip_Art_Image_2.png",
        largeImg:"/Flowers-but-better/circle/Yellow_Daffodils_PNG_Transparent_Clip_Art_Image_2.png",
        description: "Daffodils are bright yellow spring flowers, representing renewal and new beginnings.",
        checked: false,
    },
    {
        name: "Lily",
        smallImg:"/Flowers-but-better/circle/pngtree-white-lily-flower-png-image_10012327_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-white-lily-flower-png-image_10012327_2.png",
        description: "Lilies are elegant flowers, often symbolizing purity, beauty, and renewal.",
        checked: false,
    },
    {
        name: "Lavender",
        smallImg:"/Flowers-but-better/circle/lavender-png-mnh3txq1oo3ve9qw.png",
        largeImg:"/Flowers-but-better/circle/lavender-png-mnh3txq1oo3ve9qw.png",
        description: "Lavender is a fragrant flower, symbolizing calm and often used in aromatherapy.",
        checked: false,
    },
    {
        name: "Chrysanthemum",
        smallImg:"/Flowers-but-better/circle/Orange_Chrysanthemum_Flower_Transparent_Clip_Art_Image_2.png",
        largeImg:"/Flowers-but-better/circle/Orange_Chrysanthemum_Flower_Transparent_Clip_Art_Image_2.png",
        description: "Chrysanthemums are vibrant flowers often seen in autumn, symbolizing longevity.",
        checked: false,
    },
    {
        name: "Jasmine",
        smallImg:"/Flowers-but-better/circle/pngtree-jasmine-flower-ai-generated-png-image_12382601_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-jasmine-flower-ai-generated-png-image_12382601_2.png",
        description: "Jasmine is a fragrant white flower, symbolizing love, beauty, and sensuality.",
        checked: false,
    },
    {
        name: "Gerbera",
        smallImg:"/Flowers-but-better/circle/yellow_gerbera_daisy_by_jeanicebartzen27_daj9k1g-fullview_2.png",
        largeImg:"/Flowers-but-better/circle/yellow_gerbera_daisy_by_jeanicebartzen27_daj9k1g-fullview_2.png",
        description: "Gerbera daisies are vibrant flowers representing cheerfulness and innocence.",
        checked: false,
    },
    {
        name: "Poppy",
        smallImg:"/Flowers-but-better/circle/Red_Poppy_Flower_PNG_Clip_Art_Image-1096497855_2.png",
        largeImg:"/Flowers-but-better/circle/Red_Poppy_Flower_PNG_Clip_Art_Image-1096497855_2.png",
        description: "Poppies are red flowers symbolizing remembrance and peace.",
        checked: false,
    },
    {
        name: "Peony",
        smallImg:"/Flowers-but-better/circle/pngtree-pink-peony-flower-png-image_11561406_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-pink-peony-flower-png-image_11561406_2.png",
        description: "Peonies are lush flowers that symbolize prosperity, good luck, and romance.",
        checked: false,
    },
    {
        name: "Iris",
        smallImg:"/Flowers-but-better/circle/iris-flower-on-transparent-background-free-png_2.png",
        largeImg:"/Flowers-but-better/circle/iris-flower-on-transparent-background-free-png_2.png",
        description: "Iris flowers are known for their unique shape and symbolizing wisdom and faith.",
        checked: false,
    },
    {
        name: "Dahlia",
        smallImg:"/Flowers-but-better/circle/dahlia-flower-free-png_2.png",
        largeImg:"/Flowers-but-better/circle/dahlia-flower-free-png_2.png",
        description: "Dahlias are bold flowers, representing strength, beauty, and creativity.",
        checked: false,
    },
    {
        name: "Hibiscus",
        smallImg:"/Flowers-but-better/circle/pngtree-beautiful-red-hibiscus-flower-png-image_6845814_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-beautiful-red-hibiscus-flower-png-image_6845814_2.png",
        description: "Hibiscus flowers are tropical blooms, symbolizing beauty, charm, and feminine strength.",
        checked: false,
    },
    {
        name: "Zinnia",
        smallImg:"/Flowers-but-better/circle/botanical-zinnia-flower-and-leaf-isolated-on-transparent-background-free-png_2.png",
        largeImg:"/Flowers-but-better/circle/botanical-zinnia-flower-and-leaf-isolated-on-transparent-background-free-png_2.png",
        description: "Zinnias are hardy flowers known for their bright colors and symbolism of endurance.",
        checked: false,
    },
    {
        name: "Carnation",
        smallImg:"/Flowers-but-better/circle/pngtree-carnation-pink-illustration-png-image_6694653_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-carnation-pink-illustration-png-image_6694653_2.png",
        description: "Carnations are popular flowers that symbolize love, fascination, and distinction.",
        checked: false,
    },
    {
        name: "Begonia",
        smallImg:"/Flowers-but-better/circle/pngtree-begonia-everblooming-red-flower-png-image_13520306_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-begonia-everblooming-red-flower-png-image_13520306_2.png",
        description: "Begonias are known for their colorful flowers and are often associated with caution and discretion.",
        checked: false,
    },
    {
        name: "Calla Lily",
        smallImg:"/Flowers-but-better/circle/pngtree-watercolor-floral-bouquet-illustration-calla-lily-flowers-ai-generated-png-image_11579870_2.png",
        largeImg:"/Flowers-but-better/circle/pngtree-watercolor-floral-bouquet-illustration-calla-lily-flowers-ai-generated-png-image_11579870_2.png",
        description: "Calla lilies are elegant flowers symbolizing purity and magnificence.",
        checked: false,
    },
    {
        name: "Camellia",
        smallImg:"/Flowers-but-better/circle/camellia-5562259_1280_2.png",
        largeImg:"/Flowers-but-better/circle/camellia-5562259_1280_2.png",
        description: "Camellias are stunning flowers symbolizing love, affection, and admiration.",
        checked: false,
    }
];

export default cards;
