const cards = [
    {
        name: "Rose",
        smallImg: "https://www.pngarc.com/wp-content/uploads/2023/05/red-rose-flower-illustration-Rose-Rose-HD-leaf-color-plant-Stem-png-min.png",
        largeImg: "https://www.pngarc.com/wp-content/uploads/2023/05/red-rose-flower-illustration-Rose-Rose-HD-leaf-color-plant-Stem-png-min.png",
        description: "Roses are iconic flowers known for their beauty and fragrance, symbolizing love.",
        checked: true,
    },
    {
        name: "Tulip",
        smallImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Flowers-PNG/Tulip_Transparent_Image-1525420458.png?m=1629831664",
        largeImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Flowers-PNG/Tulip_Transparent_Image-1525420458.png?m=1629831664",
        description: "Tulips are colorful flowers, popular in gardens and symbolizing perfect love.",
        checked: false,
    },
    {
        name: "Sunflower",
        smallImg: "https://purepng.com/public/uploads/large/purepng.com-sunflowersunflowersunflower-plantsunflower-oilyellow-sunflower-1701527749038lczyn.png",
        largeImg: "https://purepng.com/public/uploads/large/purepng.com-sunflowersunflowersunflower-plantsunflower-oilyellow-sunflower-1701527749038lczyn.png",
        description: "Sunflowers are known for their large yellow petals and seeds, often associated with happiness.",
        checked: false,
    },
    {
        name: "Orchid",
        smallImg: "https://png.pngtree.com/png-vector/20231023/ourmid/pngtree-red-orchid-on-white-background-vibrant-png-image_10174647.png",
        largeImg: "https://png.pngtree.com/png-vector/20231023/ourmid/pngtree-red-orchid-on-white-background-vibrant-png-image_10174647.png",
        description: "Orchids are exotic flowers with intricate designs, symbolizing beauty and strength.",
        checked: false,
    },
    {
        name: "Daffodil",
        smallImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Spring-PNG/Yellow_Daffodils_PNG_Transparent_Clip_Art_Image.png?m=1629833275",
        largeImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Spring-PNG/Yellow_Daffodils_PNG_Transparent_Clip_Art_Image.png?m=1629833275",
        description: "Daffodils are bright yellow spring flowers, representing renewal and new beginnings.",
        checked: false,
    },
    {
        name: "Lily",
        smallImg: "https://png.pngtree.com/png-vector/20230909/ourmid/pngtree-white-lily-flower-png-image_10012327.png",
        largeImg: "https://png.pngtree.com/png-vector/20230909/ourmid/pngtree-white-lily-flower-png-image_10012327.png",
        description: "Lilies are elegant flowers, often symbolizing purity, beauty, and renewal.",
        checked: false,
    },
    {
        name: "Lavender",
        smallImg: "https://wallpapers.com/images/featured/lavender-png-mnh3txq1oo3ve9qw.jpg",
        largeImg: "https://wallpapers.com/images/featured/lavender-png-mnh3txq1oo3ve9qw.jpg",
        description: "Lavender is a fragrant flower, symbolizing calm and often used in aromatherapy.",
        checked: false,
    },
    {
        name: "Chrysanthemum",
        smallImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Flowers-PNG/Orange_Chrysanthemum_Flower_Transparent_Clip_Art_Image.png?m=1629831757",
        largeImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Flowers-PNG/Orange_Chrysanthemum_Flower_Transparent_Clip_Art_Image.png?m=1629831757",
        description: "Chrysanthemums are vibrant flowers often seen in autumn, symbolizing longevity.",
        checked: false,
    },
    {
        name: "Jasmine",
        smallImg: "https://png.pngtree.com/png-vector/20240508/ourmid/pngtree-jasmine-flower-ai-generated-png-image_12382601.png",
        largeImg: "https://png.pngtree.com/png-vector/20240508/ourmid/pngtree-jasmine-flower-ai-generated-png-image_12382601.png",
        description: "Jasmine is a fragrant white flower, symbolizing love, beauty, and sensuality.",
        checked: false,
    },
    {
        name: "Gerbera",
        smallImg: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/782c86ba-d983-40a0-861c-c19a47e67ef6/daj9k1g-a995c234-4910-40b5-9cb6-59767d6bbf03.png/v1/fill/w_1024,h_1016/yellow_gerbera_daisy_by_jeanicebartzen27_daj9k1g-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTAxNiIsInBhdGgiOiJcL2ZcLzc4MmM4NmJhLWQ5ODMtNDBhMC04NjFjLWMxOWE0N2U2N2VmNlwvZGFqOWsxZy1hOTk1YzIzNC00OTEwLTQwYjUtOWNiNi01OTc2N2Q2YmJmMDMucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.LEELizSxyUbyMxvwKAheHU61Jk_Hat32xOKEycOfLZ4",
        largeImg: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/782c86ba-d983-40a0-861c-c19a47e67ef6/daj9k1g-a995c234-4910-40b5-9cb6-59767d6bbf03.png/v1/fill/w_1024,h_1016/yellow_gerbera_daisy_by_jeanicebartzen27_daj9k1g-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTAxNiIsInBhdGgiOiJcL2ZcLzc4MmM4NmJhLWQ5ODMtNDBhMC04NjFjLWMxOWE0N2U2N2VmNlwvZGFqOWsxZy1hOTk1YzIzNC00OTEwLTQwYjUtOWNiNi01OTc2N2Q2YmJmMDMucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.LEELizSxyUbyMxvwKAheHU61Jk_Hat32xOKEycOfLZ4",
        description: "Gerbera daisies are vibrant flowers representing cheerfulness and innocence.",
        checked: false,
    },
    {
        name: "Poppy",
        smallImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Flowers-PNG/Red_Poppy_Flower_PNG_Clip_Art_Image-1096497855.png?m=1629831689",
        largeImg: "https://gallery.yopriceville.com/var/resizes/Free-Clipart-Pictures/Flowers-PNG/Red_Poppy_Flower_PNG_Clip_Art_Image-1096497855.png?m=1629831689",
        description: "Poppies are red flowers symbolizing remembrance and peace.",
        checked: false,
    },
    {
        name: "Peony",
        smallImg: "https://png.pngtree.com/png-vector/20240129/ourmid/pngtree-pink-peony-flower-png-image_11561406.png",
        largeImg: "https://png.pngtree.com/png-vector/20240129/ourmid/pngtree-pink-peony-flower-png-image_11561406.png",
        description: "Peonies are lush flowers that symbolize prosperity, good luck, and romance.",
        checked: false,
    },
    {
        name: "Iris",
        smallImg: "https://example.com/iris-small.jpg",
        largeImg: "https://example.com/iris-large.jpg",
        description: "Iris flowers are known for their unique shape and symbolizing wisdom and faith.",
        checked: false,
    },
    {
        name: "Dahlia",
        smallImg: "https://example.com/dahlia-small.jpg",
        largeImg: "https://example.com/dahlia-large.jpg",
        description: "Dahlias are bold flowers, representing strength, beauty, and creativity.",
        checked: false,
    },
    {
        name: "Hibiscus",
        smallImg: "https://example.com/hibiscus-small.jpg",
        largeImg: "https://example.com/hibiscus-large.jpg",
        description: "Hibiscus flowers are tropical blooms, symbolizing beauty, charm, and feminine strength.",
        checked: false,
    },
    {
        name: "Zinnia",
        smallImg: "https://example.com/zinnia-small.jpg",
        largeImg: "https://example.com/zinnia-large.jpg",
        description: "Zinnias are hardy flowers known for their bright colors and symbolism of endurance.",
        checked: false,
    },
    {
        name: "Carnation",
        smallImg: "https://example.com/carnation-small.jpg",
        largeImg: "https://example.com/carnation-large.jpg",
        description: "Carnations are popular flowers that symbolize love, fascination, and distinction.",
        checked: false,
    },
    {
        name: "Begonia",
        smallImg: "https://example.com/begonia-small.jpg",
        largeImg: "https://example.com/begonia-large.jpg",
        description: "Begonias are known for their colorful flowers and are often associated with caution and discretion.",
        checked: false,
    },
    {
        name: "Calla Lily",
        smallImg: "https://example.com/calla-lily-small.jpg",
        largeImg: "https://example.com/calla-lily-large.jpg",
        description: "Calla lilies are elegant flowers symbolizing purity and magnificence.",
        checked: false,
    },
    {
        name: "Camellia",
        smallImg: "https://example.com/camellia-small.jpg",
        largeImg: "https://example.com/camellia-large.jpg",
        description: "Camellias are stunning flowers symbolizing love, affection, and admiration.",
        checked: false,
    }
];

export default cards;
