const cards = [
    {
        name: "Rose",
        smallImg: "https://example.com/rose-small.jpg",
        largeImg: "https://example.com/rose-large.jpg",
        description: "Roses are iconic flowers known for their beauty and fragrance, symbolizing love.",
        checked: true,
    },
    {
        name: "Tulip",
        smallImg: "https://example.com/tulip-small.jpg",
        largeImg: "https://example.com/tulip-large.jpg",
        description: "Tulips are colorful flowers, popular in gardens and symbolizing perfect love.",
        checked: false,
    },
    {
        name: "Sunflower",
        smallImg: "https://example.com/sunflower-small.jpg",
        largeImg: "https://example.com/sunflower-large.jpg",
        description: "Sunflowers are known for their large yellow petals and seeds, often associated with happiness.",
        checked: false,
    },
    {
        name: "Orchid",
        smallImg: "https://example.com/orchid-small.jpg",
        largeImg: "https://example.com/orchid-large.jpg",
        description: "Orchids are exotic flowers with intricate designs, symbolizing beauty and strength.",
        checked: false,
    },
    {
        name: "Daffodil",
        smallImg: "https://example.com/daffodil-small.jpg",
        largeImg: "https://example.com/daffodil-large.jpg",
        description: "Daffodils are bright yellow spring flowers, representing renewal and new beginnings.",
        checked: false,
    },
    {
        name: "Lily",
        smallImg: "https://example.com/lily-small.jpg",
        largeImg: "https://example.com/lily-large.jpg",
        description: "Lilies are elegant flowers, often symbolizing purity, beauty, and renewal.",
        checked: false,
    },
    {
        name: "Lavender",
        smallImg: "https://example.com/lavender-small.jpg",
        largeImg: "https://example.com/lavender-large.jpg",
        description: "Lavender is a fragrant flower, symbolizing calm and often used in aromatherapy.",
        checked: false,
    },
    {
        name: "Chrysanthemum",
        smallImg: "https://example.com/chrysanthemum-small.jpg",
        largeImg: "https://example.com/chrysanthemum-large.jpg",
        description: "Chrysanthemums are vibrant flowers often seen in autumn, symbolizing longevity.",
        checked: false,
    },
    {
        name: "Jasmine",
        smallImg: "https://example.com/jasmine-small.jpg",
        largeImg: "https://example.com/jasmine-large.jpg",
        description: "Jasmine is a fragrant white flower, symbolizing love, beauty, and sensuality.",
        checked: false,
    },
    {
        name: "Gerbera",
        smallImg: "https://example.com/gerbera-small.jpg",
        largeImg: "https://example.com/gerbera-large.jpg",
        description: "Gerbera daisies are vibrant flowers representing cheerfulness and innocence.",
        checked: false,
    },
    {
        name: "Poppy",
        smallImg: "https://example.com/poppy-small.jpg",
        largeImg: "https://example.com/poppy-large.jpg",
        description: "Poppies are red flowers symbolizing remembrance and peace.",
        checked: false,
    },
    {
        name: "Peony",
        smallImg: "https://example.com/peony-small.jpg",
        largeImg: "https://example.com/peony-large.jpg",
        description: "Peonies are lush flowers that symbolize prosperity, good luck, and romance.",
        checked: false,
    },
    {
        name: "Iris",
        smallImg: "https://example.com/iris-small.jpg",
        largeImg: "https://example.com/iris-large.jpg",
        description: "Iris flowers are known for their unique shape and symbolizing wisdom and faith.",
        checked: false,
    },
    {
        name: "Dahlia",
        smallImg: "https://example.com/dahlia-small.jpg",
        largeImg: "https://example.com/dahlia-large.jpg",
        description: "Dahlias are bold flowers, representing strength, beauty, and creativity.",
        checked: false,
    },
    {
        name: "Hibiscus",
        smallImg: "https://example.com/hibiscus-small.jpg",
        largeImg: "https://example.com/hibiscus-large.jpg",
        description: "Hibiscus flowers are tropical blooms, symbolizing beauty, charm, and feminine strength.",
        checked: false,
    },
    {
        name: "Zinnia",
        smallImg: "https://example.com/zinnia-small.jpg",
        largeImg: "https://example.com/zinnia-large.jpg",
        description: "Zinnias are hardy flowers known for their bright colors and symbolism of endurance.",
        checked: false,
    },
    {
        name: "Carnation",
        smallImg: "https://example.com/carnation-small.jpg",
        largeImg: "https://example.com/carnation-large.jpg",
        description: "Carnations are popular flowers that symbolize love, fascination, and distinction.",
        checked: false,
    },
    {
        name: "Begonia",
        smallImg: "https://example.com/begonia-small.jpg",
        largeImg: "https://example.com/begonia-large.jpg",
        description: "Begonias are known for their colorful flowers and are often associated with caution and discretion.",
        checked: false,
    },
    {
        name: "Calla Lily",
        smallImg: "https://example.com/calla-lily-small.jpg",
        largeImg: "https://example.com/calla-lily-large.jpg",
        description: "Calla lilies are elegant flowers symbolizing purity and magnificence.",
        checked: false,
    },
    {
        name: "Camellia",
        smallImg: "https://example.com/camellia-small.jpg",
        largeImg: "https://example.com/camellia-large.jpg",
        description: "Camellias are stunning flowers symbolizing love, affection, and admiration.",
        checked: false,
    }
];

export default cards;
