//i put it here cuz too big
const cards = [
    {
        name: "Bulbasaur",
        smallImg: "https://i.pinimg.com/736x/49/30/22/493022d455070861e46d7298036190a4.jpg",
        largeImg: "https://i.pinimg.com/736x/49/30/22/493022d455070861e46d7298036190a4.jpg",
        description: "Bulbasaur is a grass/poison type Pokémon that evolves into Ivysaur.",
        checked: true,
    },
    {
        name: "Charmander",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/charmander-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/charmander-l.png",
        description: "Charmander is the fire-type starter Pokémon first seen in Pokémon Red/Blue.",
        checked: false,
    },
    {
        name: "Squirtle",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/squirtle-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/squirtle-l.png",
        description: "Squirtle is a Water-type starter Pokémon from the original Pokémon Red/Blue.",
        checked: false,
    },
    {
        name: "Pikachu",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/pikachu-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/pikachu-l.png",
        description: "Pikachu is an Electric-type Pokémon and mascot of the Pokémon series.",
        checked: false,
    },
    {
        name: "Jigglypuff",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/jigglypuff-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/jigglypuff-l.png",
        description: "Jigglypuff is a Normal/Fairy Pokémon known for its lullaby that puts others to sleep.",
        checked: false,
    },
    {
        name: "Meowth",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/meowth-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/meowth-l.png",
        description: "Meowth is a Normal-type Pokémon and the companion of Team Rocket.",
        checked: false,
    },
    {
        name: "Psyduck",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/psyduck-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/psyduck-l.png",
        description: "Psyduck is a Water-type Pokémon that suffers from constant headaches.",
        checked: false,
    },
    {
        name: "Eevee",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/eevee-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/eevee-l.png",
        description: "Eevee is a Normal-type Pokémon with the ability to evolve into many forms.",
        checked: false,
    },
    {
        name: "Snorlax",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/snorlax-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/snorlax-l.png",
        description: "Snorlax is a Normal-type Pokémon known for its size and love of sleep.",
        checked: false,
    },
    {
        name: "Gengar",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/gengar-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/gengar-l.png",
        description: "Gengar is a Ghost/Poison Pokémon with a mischievous nature.",
        checked: false,
    },
    {
        name: "Dragonite",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/dragonite-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/dragonite-l.png",
        description: "Dragonite is a Dragon/Flying Pokémon known for its speed and strength.",
        checked: false,
    },
    {
        name: "Mewtwo",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/mewtwo-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/mewtwo-l.png",
        description: "Mewtwo is a Psychic Pokémon created by genetic manipulation.",
        checked: false,
    },
    {
        name: "Caterpie",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/caterpie-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/caterpie-l.png",
        description: "Caterpie is a Bug-type Pokémon that evolves into Metapod.",
        checked: false,
    },
    {
        name: "Butterfree",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/butterfree-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/butterfree-l.png",
        description: "Butterfree is the final evolution of Caterpie, a Bug/Flying-type Pokémon.",
        checked: false,
    },
    {
        name: "Rattata",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/rattata-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/rattata-l.png",
        description: "Rattata is a Normal-type Pokémon known for its quickness.",
        checked: false,
    },
    {
        name: "Zubat",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/zubat-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/zubat-l.png",
        description: "Zubat is a Poison/Flying-type Pokémon often found in caves.",
        checked: false,
    },
    {
        name: "Oddish",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/oddish-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/oddish-l.png",
        description: "Oddish is a Grass/Poison Pokémon that evolves into Gloom.",
        checked: false,
    },
    {
        name: "Venonat",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/venonat-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/venonat-l.png",
        description: "Venonat is a Bug/Poison Pokémon that evolves into Venomoth.",
        checked: false,
    },
    {
        name: "Machop",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/machop-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/machop-l.png",
        description: "Machop is a Fighting-type Pokémon known for its strength.",
        checked: false,
    },
    {
        name: "Geodude",
        smallImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/geodude-s.png",
        largeImg: "https://raw.githubusercontent.com/cbolson/assets/refs/heads/main/codepen/pokemon/geodude-l.png",
        description: "Geodude is a Rock/Ground Pokémon that evolves into Graveler.",
        checked: false,
    },
    ];

export default cards;